CREATE TABLE ACTIVEMQ_MSGS(
	ID BIGINT NOT NULL,
	CONTAINER VARCHAR(250),
	MSGID_PROD VARCHAR(250),
	MSGID_SEQ BIGINT,
	EXPIRATION BIGINT,
	MSG BLOB,
	PRIORITY BIGINT,
	XID VARCHAR(250),
	PRIMARY KEY ( ID )
	)
;
CREATE INDEX ACTIVEMQ_MSGS_MIDX ON ACTIVEMQ_MSGS (MSGID_PROD,MSGID_SEQ);
CREATE INDEX ACTIVEMQ_MSGS_CIDX ON ACTIVEMQ_MSGS (CONTAINER);
CREATE INDEX ACTIVEMQ_MSGS_EIDX ON ACTIVEMQ_MSGS (EXPIRATION);
CREATE INDEX ACTIVEMQ_MSGS_PIDX ON ACTIVEMQ_MSGS (PRIORITY);

CREATE TABLE ACTIVEMQ_ACKS(
	CONTAINER VARCHAR(250) NOT NULL,
	SUB_DEST VARCHAR(250),
	CLIENT_ID VARCHAR(250) NOT NULL,
	SUB_NAME VARCHAR(250) NOT NULL,
	SELECTOR VARCHAR(250),
	LAST_ACKED_ID BIGINT,
	PRIORITY BIGINT DEFAULT 5 NOT NULL,
	XID VARCHAR(250),
	PRIMARY KEY (CONTAINER, CLIENT_ID, SUB_NAME, PRIORITY)
	)
;
CREATE INDEX ACTIVEMQ_MSGS_XIDX ON ACTIVEMQ_MSGS (XID);
CREATE INDEX ACTIVEMQ_ACKS_XIDX ON ACTIVEMQ_ACKS (XID);

CREATE TABLE ACTIVEMQ_LOCK(
	ID BIGINT NOT NULL,
	TIME BIGINT,
	BROKER_NAME VARCHAR(250),
	PRIMARY KEY (ID)
	)
;

INSERT INTO ACTIVEMQ_LOCK(ID) VALUES (1);