name: Java CI

#on: [push]
on:
  push:
    branches:
      - fake-branch-6126bea4-e097-4668-993f-31d319f71f05
      #- main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
